import tkinter as tk
from tkinter import*
import random
import time
import tkinter.scrolledtext as tkst
window = tk.Tk()
window.geometry("2000x4000")
window.title("list of zonal railway")
window.config(bg="black")
scrollbar = Scrollbar(window)
scrollbar.pack(side = RIGHT, fill = Y)
f1 = Frame(window,width = 1000,height=900,relief=SUNKEN,bg="white")
f1.place(x=100,y=10)
label1 =tk.Label(f1,text="List of Zonal Railways in India",padx=20,pady=20,font = ('Times New Roman', 36,),bg="white",fg="blue",width=40,height=1,relief=SUNKEN,borderwidth=0)
label1.place(x=10,y=0)
label2 =tk.Label(f1,text="S.No.",font = ('Times New Roman',18),padx=20,pady=20,bg="white",fg="black",width=5,height=0,relief=SUNKEN,borderwidth=1,)
label2.place(x=20,y=100)
label3 =tk.Label(f1,text="Zonal Name",font = ('Times New Roman',18),padx=20,pady=20,bg="white",fg="black",width=15,height=0,relief=SUNKEN,borderwidth=1,)
label3.place(x=130,y=100)
label4 =tk.Label(f1,text="Abb.",font = ('Times New Roman',18),padx=20,pady=20,bg="white",fg="black",width=10,height=0,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=100)
label5 =tk.Label(f1,text="Headquarters",font = ('Times New Roman',18),padx=20,pady=20,bg="white",fg="black",width=10,height=0,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=100)
label6 =tk.Label(f1,text="Divisions",font = ('Times New Roman',18),padx=20,pady=20,bg="white",fg="black",width=15,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=100)
label7 =tk.Label(f1,text="1",font = ('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=170)
label8 =tk.Label(f1,text="Central",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=170)
label4 =tk.Label(f1,text="CR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=170)
label5 =tk.Label(f1,text="Mumbai",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=170)
label6 =tk.Label(f1,text="Mumbai, Bhusawal, Pune,\n Solapur,Nagpur",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=170)
label7 =tk.Label(f1,text="2",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=220)
label8 =tk.Label(f1,text="East Central",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=220)
label4 =tk.Label(f1,text="ECR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=220)
label5 =tk.Label(f1,text="Hajipur",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=220)
label6 =tk.Label(f1,text=" Danapur,Dhanbad,Mughalsarai,\nSamastipur,Sonpur",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=220)
label7 =tk.Label(f1,text="3",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=270)
label8 =tk.Label(f1,text="East Coast",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=270)
label4 =tk.Label(f1,text="ECoR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=270)
label5 =tk.Label(f1,text="Bhubaneswar",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=270)
label6 =tk.Label(f1,text=" Khurda Road, Sambalpur,\nVisakhapatnam",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=270)
label7 =tk.Label(f1,text="4",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=320)
label8 =tk.Label(f1,text="Eastern",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=320)
label4 =tk.Label(f1,text="ER",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=320)
label5 =tk.Label(f1,text="Kolkata",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=320)
label6 =tk.Label(f1,text="Howrah, Sealdah, Asansol,\n Malda",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=320)
label7 =tk.Label(f1,text="5",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=370)
label8 =tk.Label(f1,text="North Central",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=370)
label4 =tk.Label(f1,text="NCR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=370)
label5 =tk.Label(f1,text="Allahabad",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=370)
label6 =tk.Label(f1,text="Allahabad, Agra,\n Jhansi",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=370)
label7 =tk.Label(f1,text="6",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=420)
label8 =tk.Label(f1,text="North Eastern",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=420)
label4 =tk.Label(f1,text="NER",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=420)
label5 =tk.Label(f1,text="Gorakhpur",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=420)
label6 =tk.Label(f1,text="Izzatnagar, Lucknow,\n Varanasi",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=420)
label7 =tk.Label(f1,text="7",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=470)
label8 =tk.Label(f1,text="North Western",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=470)
label4 =tk.Label(f1,text="NWR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=470)
label5 =tk.Label(f1,text="Jaipur",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=470)
label6 =tk.Label(f1,text="Jaipur, Ajmer, Bikaner,\n Jodhpur",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=470)
label7 =tk.Label(f1,text="8",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=520)
label8 =tk.Label(f1,text="Northeast Frontier",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=520)
label4 =tk.Label(f1,text="NFR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=520)
label5 =tk.Label(f1,text="Guwahati",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=520)
label6 =tk.Label(f1,text="Alipurduar, Katihar, Lumding,\nRangia, Tinsukia",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=520)
label7 =tk.Label(f1,text="9",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=520)
label8 =tk.Label(f1,text="Northern",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=520)
label4 =tk.Label(f1,text="NR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=520)
label5 =tk.Label(f1,text="Delhi",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=520)
label6 =tk.Label(f1,text="Delhi,Ambala,Firozpur,\n Lucknow,Moradabad",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=520)
label7 =tk.Label(f1,text="10",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=570)
label8 =tk.Label(f1,text="South Central",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=570)
label4 =tk.Label(f1,text="SCR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=570)
label5 =tk.Label(f1,text="Secunderabad",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=570)
label6 =tk.Label(f1,text="Hyderabad,Guntakal\nGuntur,Nanded,Vijayawada",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=570)
label7 =tk.Label(f1,text="11",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=620)
label8 =tk.Label(f1,text="South East Central",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=620)
label4 =tk.Label(f1,text="SCER",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=620)
label5 =tk.Label(f1,text="Bilaspur",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=620)
label6 =tk.Label(f1,text="Bilaspur, Raipur,\n Nagpur",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=620)
label7 =tk.Label(f1,text="12",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=670)
label8 =tk.Label(f1,text="South Eastern",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=670)
label4 =tk.Label(f1,text="SER",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=670)
label5 =tk.Label(f1,text="Kolkata",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=670)
label6 =tk.Label(f1,text="Adra, Chakradharpur,\n Kharagpur,Ranchi",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=670)
label7 =tk.Label(f1,text="13",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=720)
label8 =tk.Label(f1,text="South Western",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=720)
label4 =tk.Label(f1,text="SWR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=720)
label5 =tk.Label(f1,text="Hubli",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=720)
label6 =tk.Label(f1,text="Hubli, Bangalore,\n Mysore",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=720)
label7 =tk.Label(f1,text="14",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=770)
label8 =tk.Label(f1,text="Southern",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=770)
label4 =tk.Label(f1,text="SR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=770)
label5 =tk.Label(f1,text="Channai",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=770)
label6 =tk.Label(f1,text="Madurai,Palakkad,Salem,\nTiruchchirapalli,Thiruvanathapuram",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=770)
label7 =tk.Label(f1,text="15",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=820)
label8 =tk.Label(f1,text="West Central",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=820)
label4 =tk.Label(f1,text="WCR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=820)
label5 =tk.Label(f1,text="Jabalpur",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=820)
label6 =tk.Label(f1,text="Jabalpur, Bhopal,\n Kota",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=820)
label7 =tk.Label(f1,text="16",font=('Times New Roman',14),bg="white",fg="black",width=10,height=2,relief=SUNKEN,borderwidth=1,)
label7.place(x=20,y=870)
label8 =tk.Label(f1,text="Western",font=('Times New Roman',14),bg="white",fg="blue",width=23,height=2,relief=SUNKEN,borderwidth=1,)
label8.place(x=130,y=870)
label4 =tk.Label(f1,text="WR",font = ('Times New Roman',14),bg="white",fg="black",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label4.place(x=375,y=870)
label5 =tk.Label(f1,text="Mumbai",font = ('Times New Roman',14),bg="white",fg="blue",width=17,height=2,relief=SUNKEN,borderwidth=1,)
label5.place(x=550,y=870)
label6 =tk.Label(f1,text="Mumbai Central, Ratlam,\nAhmedabad, Rajkot, \nBhavnagar,Vadodara",font = ('Times New Roman',14),bg="white",fg="blue",width=23,height=0,relief=SUNKEN,borderwidth=1,)
label6.place(x=725,y=870)
window.mainloop()
